### ISSUE TITLE
Creating snapshots trough API does not work

### ISSUE THREAD

**Issue by Nitradamus** [ATIX-AG/foreman_snapshot_management#36]
Hello,

While trying to create a snapshot trough the API it fails with the following message:

curl -k -u user:pass -H "Accept: version=2,application/json" -H "Content-Type: application/json" -X POST ${FOREMAN_URL}/api/hosts/${HOST}/snapshots -d '
{
  "snapshot":{
    "name":"test",
    "description":"abc"
  }
}'

{
  "error": {"message":"snapshot is a required parameter"}
}

Foreman logs when doing the POST:

```
2018-11-29T15:46:13 [I|app|] Started POST "/api/hosts/host.com/snapshots" for 10.101.101.2 at 2018-11-29 15:46:13 +0100
2018-11-29T15:46:13 [I|app|7fdf2] Processing by Api::V2::SnapshotsController#create as JSON
2018-11-29T15:46:13 [I|app|7fdf2]   Parameters: {"snapshot"=>{"name"=>"test", "description"=>"abc"}, "apiv"=>"v2", "host_id"=>"host.com"}
2018-11-29T15:46:13 [I|app|7fdf2] Authorized user ops(ops)
2018-11-29T15:46:13 [I|app|7fdf2] Current user set to ops (admin)
2018-11-29T15:46:13 [W|app|7fdf2] Action failed
ArgumentError: snapshot is a required parameter
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_snapshot_management-1.5.0/app/models/concerns/fog_extensions/vsphere/snapshots/real.rb:29:in `rename_snapshot'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_snapshot_management-1.5.0/app/models/foreman_snapshot_management/vmware_extensions.rb:45:in `update_snapshot'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_snapshot_management-1.5.0/app/models/foreman_snapshot_management/snapshot.rb:130:in `block (2 levels) in save'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_snapshot_management-1.5.0/app/models/foreman_snapshot_management/snapshot.rb:161:in `handle_snapshot_errors'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_snapshot_management-1.5.0/app/models/foreman_snapshot_management/snapshot.rb:127:in `block in save'
/opt/theforeman/tfm-ror52/root/usr/share/gems/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_snapshot_management-1.5.0/app/models/foreman_snapshot_management/snapshot.rb:126:in `save'
/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_snapshot_management-1.5.0/app/controllers/api/v2/snapshots_controller.rb:37:in `create'
/opt/theforeman/tfm-ror52/root/usr/share/gems/gems/actionpack-5.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/opt/theforeman/tfm-ror52/root/usr/share/gems/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:194:in `process_action'
/opt/theforeman/tfm-ror52/root/usr/share/gems/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/opt/theforeman/tfm-ror52/root/usr/share/gems/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/opt/theforeman/tfm-ror52/root/usr/share/gems/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
```

I've tried the patches suggested in the other issue #34 to no avail.. any idea what could be wrong?

**Comment by mdellweg** [comment]
Can you try with version 1.5.1 again?

**Comment by m-bucher** [comment]
Yes, this is fixed in v1.5.1 - by eb5495818e2b2e86d514e992ae3fdb324e324eaa to be precise :-)
There was an error that the API tried to update instead of create a snapshot and since there was no snapshot specified to be updated, the error is shown.

**Comment by Nitradamus** [comment]
Thanks  for the suggestions, i've tried manually installing the 1.5.1 version since the rpm package is still on 1.5.0 (tfm-rubygem-foreman_snapshot_management-1.5.0-3.fm1_20.el7.noarch.rpm) but couldn't get it to function properly, can you maybe point me in the right direction?

Thanks again :)

**Comment by m-bucher** [comment]
@Nitradamus There is an RPM in the nightly-build-repository you could try: https://yum.theforeman.org/plugins/nightly/el7/x86_64/tfm-rubygem-foreman_snapshot_management-1.5.1-1.fm1_21.el7.noarch.rpm

I'll look into getting the version into the recent releases.
